// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetAppID() {
    let $resultPromise = /** @type {any} */($Call.ByID(2200334524));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetBigImage() {
    let $resultPromise = /** @type {any} */($Call.ByID(1528276745));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetBigImageDetails() {
    let $resultPromise = /** @type {any} */($Call.ByID(2921903729));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetDiscordDetails() {
    let $resultPromise = /** @type {any} */($Call.ByID(1740260852));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetDiscordState() {
    let $resultPromise = /** @type {any} */($Call.ByID(1539453395));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetSmallImage() {
    let $resultPromise = /** @type {any} */($Call.ByID(1004567358));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetSmallImageDetails() {
    let $resultPromise = /** @type {any} */($Call.ByID(3288806500));
    return $resultPromise;
}

/**
 * @param {string} appId
 * @param {string} state
 * @param {string} details
 * @param {string} bigImage
 * @param {string} bigImageDetails
 * @param {string} smallImage
 * @param {string} smallImageDetails
 * @returns {Promise<string> & { cancel(): void }}
 */
export function UpdatePresence(appId, state, details, bigImage, bigImageDetails, smallImage, smallImageDetails) {
    let $resultPromise = /** @type {any} */($Call.ByID(896545158, appId, state, details, bigImage, bigImageDetails, smallImage, smallImageDetails));
    return $resultPromise;
}
